/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.GridLayout;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import clases.Automata;

/**
 *
 * @author sandra
 */
public class Interfaz extends javax.swing.JFrame
{

//    ArrayList<JTextField> alfabeto;
    int indice;
    JTextField letra;
    JLabel label;
    JTextField[] alfabeto;
    JLabel[] renglon;
    JLabel[] columna;
    JComboBox[][] combos;
    JComboBox combo;
    String[] estados;
    int testado;

    /**
     * Creates new form interfaz
     */
    public Interfaz()
    {
        initComponents();
        alfabeto = new JTextField[100];
//        alfabeto = new ArrayList<>();
        indice = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelesta = new javax.swing.JPanel();
        txtEstado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelcolum = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        panelRen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alfabeto: ");

        panel.setLayout(new java.awt.GridLayout(0, 5));
        jScrollPane1.setViewportView(panel);

        btnAgregar.setText("+");
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText("-");
        btnQuitar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitarActionPerformed(evt);
            }
        });

        jLabel2.setText("No. Estados");

        panelesta.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(panelesta);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        panelcolum.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane3.setViewportView(panelcolum);

        panelRen.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane5.setViewportView(panelRen);

        jLabel3.setText("Cadena a analizar");

        jButton3.setText("Analizar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Esperando cadena");

        jLabel5.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnQuitar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnQuitar))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        letra = new JTextField();
//        panel.add(letra);
//        alfabeto.add(indice, letra);
//        indice++;
//        panel.updateUI();
        panel.add(letra);
        alfabeto[indice] = letra;
        indice++;
        panel.updateUI();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitarActionPerformed
    {//GEN-HEADEREND:event_btnQuitarActionPerformed
        if (indice >0)
        {
            indice--;
            panel.remove(indice);
            panel.updateUI();
            
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelcolum.removeAll();
        panelesta.removeAll();
        panelRen.removeAll();
        boolean correcto = false;
//if(Validaciones.Valida.RepetirAlfabeto(valor, alfabeto, indice, ERROR)){
//
//}
        if (alfabeto[0] == null)
        {
            JOptionPane.showMessageDialog(null, "Alfabeto no valido", "Error", JOptionPane.ERROR_MESSAGE);
        } else
        {

            String[] al = reduce();

            for (int i = 0; i < al.length - 1; i++)
            {

                if (al[i].length() == 1)
                {

                } else
                {
                    JOptionPane.showMessageDialog(null, "Alfabeto no valido", "Error", JOptionPane.ERROR_MESSAGE);
                    correcto = false;
                    break;
                }
            }
            try
            {
                Integer.parseInt(txtEstado.getText());
                correcto = true;

            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Numero de estados incorrecto", "Error", JOptionPane.ERROR_MESSAGE);

            }

        }

        if (correcto)
        {
            jButton3.setEnabled(true);

            extraerText();
            estado();
            opciones();
        } else
        {
            jButton3.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        int al = 1;
        for (int i = 0; i < alfabeto.length; i++)
        {
            if (alfabeto[i] != null)
            {
                al++;
            } else
            {
                break;
            }
        }
        String[] alfa = new String[al];

        for (int i = 0; i < alfabeto.length; i++)
        {
            if (alfabeto[i] != null)
            {
                alfa[i] = alfabeto[i].getText();
                System.out.println(alfabeto[i].getText());
            } else
            {
                break;
            }
        }

        String matriz[][] = new String[estados.length][alfa.length];

        matriz[0] = alfa;

        for (int i = 1; i < matriz.length; i++)
        {
            for (int j = 0; j < matriz[i].length; j++)
            {
                if (j < matriz[i].length - 1)
                {
                    if (combos[i - 1][j].getSelectedIndex() != 0)
                    {
                        matriz[i][j] = combos[i - 1][j].getSelectedIndex() + "";
                    } else
                    {
                        matriz[i][j] = null;
                    }
                } else
                {
                    matriz[i][j] = combos[i - 1][j].getSelectedIndex() + "";
                }

            }

        }
        String resultado = Automata.automata(matriz, jTextField1.getText());

        jLabel4.setText(resultado);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    public void extraerText()
    {
        String[] aTexto = new String[indice + 1];
        //renglon= new JLabel[indice];
        //Filas Columnas
        panelRen.setLayout(new GridLayout(1, indice));
        for (int i = 0; i < indice + 1; i++)
        {
            if (i < indice)
            {

                aTexto[i] = alfabeto[i].getText();
                System.out.println("Texto: " + aTexto[i]);
                label = new JLabel(aTexto[i]);

            } else
            {

                label = new JLabel("S/N");

                //renglon[i]=label;
            }
            panelRen.add(label);
            panelRen.updateUI();
        }
        //return aTexto;
    }

    public void estado()
    {
        testado = Integer.parseInt(txtEstado.getText());
        estados = new String[testado + 1];
        columna = new JLabel[testado];
        panelcolum.setLayout(new GridLayout(testado, 1));
        for (int i = 0; i < testado; i++)
        {
            if (i == 0)
            {
                estados[i] = ("null");
            }
            label = new JLabel("S" + i);

            estados[i + 1] = ("S" + i);
            panelcolum.add(label);

            columna[i] = label;
            panelcolum.updateUI();

        }

    }

    public void opciones()
    {
        combos = new JComboBox[testado][indice + 1];
        panelesta.setLayout(new GridLayout(testado, indice));
        for (int i = 0; i < testado; i++)
        {
            for (int j = 0; j < indice + 1; j++)
            {
                if (j < indice)
                {
                    combo = new JComboBox(estados);
                    // for (int k = 0; k < testado; k++) {
                    combos[i][j] = combo;

                } else
                {
                    String aceptacion[] =
                    {
                        "0", "1"
                    };
                    combo = new JComboBox(aceptacion);
                    // for (int k = 0; k < testado; k++) {
                    combos[i][j] = combo;

                }
                panelesta.add(combo);
                panelesta.updateUI();
                // }
            }
        }
    }

    public String[] reduce()
    {
        int al = 1;
        for (int i = 0; i < alfabeto.length; i++)
        {
            if (alfabeto[i] != null)
            {
                al++;
            } else
            {
                break;
            }
        }
        String[] alfa = new String[al];

        for (int i = 0; i < alfabeto.length; i++)
        {
            if (alfabeto[i] != null)
            {
                alfa[i] = alfabeto[i].getText();
                System.out.println(alfabeto[i].getText());
            } else
            {
                break;
            }
        }
        return alfa;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelRen;
    private javax.swing.JPanel panelcolum;
    private javax.swing.JPanel panelesta;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
